### ISSUE TITLE
[BUG] Cppcheck Issues

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/DaedalusX64-vitaGL#60]
Describe the bug
A number of code bugs found with Cppcheck, some might be ignored, but raising just in ase

To Reproduce
Run Cppcheck

Expected behavior
Bugs are fixed or ignored

Screenshots
Added the top ones that look interesting
![image](https://user-images.githubusercontent.com/283203/81545563-fb4d7880-9370-11ea-8f81-c18461e5b9a7.png)
![image](https://user-images.githubusercontent.com/283203/81545613-0c968500-9371-11ea-931b-ba87a79df579.png)
Device:
 - Device: [e.g. PSP Model or VITA]
 - FW:[e.g. Current System Firmware]
 - Daedalus Version [e.g. 1.1.6]

Additional context
[vitan64.txt](https://github.com/Rinnegatamante/DaedalusX64-vitaGL/files/4608692/vitan64.txt)

**Comment by Rinnegatamante** [comment]
Thanks for this, i'll take a closer look at all these

**Comment by Rinnegatamante** [comment]
Everything important should be solved now.

**Comment by Sarkie** [comment]
Just in case you missed a few, it looks a lot better now:
![image](https://user-images.githubusercontent.com/283203/81583802-c873a680-93a9-11ea-9285-9ea02fd2935e.png)

**Comment by Sarkie** [comment]
@Rinnegatamante in case you missed that, ^^ and also these are the latest. 
![image](https://user-images.githubusercontent.com/283203/83075455-cc6f1c00-a06b-11ea-884f-620431831d5d.png)

**Comment by Rinnegatamante** [comment]
The miniz one is irrelevant since we don't have passworded zips support.

**Comment by Sarkie** [comment]
Yeah true, the resource leaks looked interesting, but didn't know if true
